### PR TITLE
Polish version and updated readme

### PR DESCRIPTION
**Pull request by shrike82**
- mod name, description and options translated to Polish
- readme updated visually and added a link to Polish version
- Polish version of readme

### CODE REVIEW

**Comment by cech12** [comment]
Hey I like your work. 
But the format of the readme file is not standard. I will change it a bit and then you can use that for the other mods. :)

**Comment by cech12** [comment]
Okay I have changed the format. :)

**Comment by shrike82** [comment]
I have searched the Internet and using html4 is the only was Github allows to enchance those files - like center alignment or images. I wanted to also change languages to flags but since you want to use plain Text, I wont do that.

**Comment by cech12** [comment]
Thanks for your research. :) I think the readability of plain text readme files is better. And the benefit not that big, too. By the way, images are also possible in the plain text format. ;)

**Pull request merged**
